---
# Verify uv is present (handled by recent ANXS.python)
- name: "Ensure uv is present"
  ansible.builtin.command:
    cmd: uv --version
  changed_when: false
  failed_when: uv_check.rc != 0
  register: uv_check

- name: "Install dependency packages for Linux"
  ansible.builtin.apt:
    pkg: "{{ dupwrap_debian_pkgs }}"
    state: present
  when: ansible_os_family == 'Debian'

- name: "Install Focal build dependencies for lxml"
  ansible.builtin.apt:
    pkg: "{{ dupwrap_focal_build_pkgs }}"
    state: present
  when:
    - ansible_os_family == 'Debian'
    - ansible_distribution_release == 'focal'

- name: "Install dependency packages for Mac"
  community.general.homebrew:
    pkg: "{{ dupwrap_darwin_brews }}"
    state: present
  when: ansible_os_family == 'Darwin'
