- include: "deps.yml"
- name: "remove old config"
  file:
    path: "{{dupwrap_config_prefix}}/dupwrap.conf"
    state: absent
- name: "create dupwrap config directory"
  file:
    path: "{{dupwrap_config_prefix}}/dupwrap"
    state: directory
    mode: 0770
    owner: "{{dupwrap_user}}"
    group: "{{dupwrap_group}}"    
- name: "generate configs"
  template:
    src: dupwrap.conf
    dest: "{{dupwrap_config_prefix}}/dupwrap/{{item.name}}.conf"
    owner: "{{dupwrap_user}}"
    group: "{{dupwrap_group}}"
    mode: 0640
  with_items: "{{dupwrap_backups}}"
  no_log: true
- name: install wrapper
  copy:
    src: dupwrap.sh
    dest: "{{dupwrap_bin_prefix}}/dupwrap"
    owner: "{{dupwrap_user}}"
    group: "{{dupwrap_group}}"
    mode: 0750
- name: set daily cronjob
  cron:
    cron_file: "dupwrap_backup"
    name: "YOLO nightly backup"
    special_time: daily
    state: present
    job: "bash -c '{{dupwrap_bin_prefix}}/dupwrap backup'"
    user: "{{dupwrap_user}}"
  when: "dupwrap_cron and not dupwrap_cron_verbose"
- name: set daily cronjob (verbose)
  cron:
    cron_file: "dupwrap_backup"
    name: "YOLO nightly backup"
    special_time: daily
    state: present
    job: "bash -c '{{dupwrap_bin_prefix}}/dupwrap backup -v {{dupwrap_log_prefix}}/dupwrap.log'"
    user: "{{dupwrap_user}}"
  when: "dupwrap_cron and dupwrap_cron_verbose"
- name: set cron backup prune
  cron:
    cron_file: dupwrap_prune
    name: "yolo prune backups"
    special_time: "weekly"
    state: present
    job: "bash -c '{{dupwrap_bin_prefix}}/dupwrap prune'"
    user: "{{dupwrap_user}}"
  when: dupwrap_cron
