---
- include: "deps.yml"

- name: "remove old config"
  file:
    path: "{{dupwrap_config_prefix}}/dupwrap.conf"
    state: absent

- name: "create dupwrap config directory"
  file:
    path: "{{dupwrap_config_prefix}}/dupwrap"
    state: directory
    mode: 0770
    owner: "{{dupwrap_user}}"
    group: "{{dupwrap_group}}"

- name: "generate configs"
  template:
    src: "dupwrap.conf.j2"
    dest: "{{dupwrap_config_prefix}}/dupwrap/{{item.name}}.conf"
    owner: "{{dupwrap_user}}"
    group: "{{dupwrap_group}}"
    mode: 0640
  loop: "{{dupwrap_backups}}"
  when: item.state|default("present") == "present"
  no_log: "{{dupwrap_debug|default(True)}}"

- name: "remove unwanted configs"
  file:
    path: "{{dupwrap_config_prefix}}/dupwrap/{{item.name}}.conf"
    state: absent
  loop: "{{dupwrap_backups}}"
  when: item.state|default("present") == "absent"

- name: "install wrapper"
  copy:
    src: "dupwrap.sh"
    dest: "{{dupwrap_bin_prefix}}/dupwrap"
    owner: "{{dupwrap_user}}"
    group: "{{dupwrap_group}}"
    mode: 0750

- name: "remove old nightly cronjob"
  file:
    path: "/etc/cron.d/dupwrap_backup"
    state: "absent"

- name: "set daily cronjob"
  cron:
    cron_file: "dupwrap-backup-{{item.name}}"
    name: "YOLO nightly backup"
    special_time: "daily"
    job: >
      bash -c '{{dupwrap_bin_prefix}}/dupwrap backup -p {{ item.name }}
      {% if dupwrap_cron_verbose -%}
      -v &>> {{dupwrap_log_prefix}}/dupwrap.log
      {% else %}
      -q
      {%- endif -%}'
    user: "{{dupwrap_user}}"
    state: "{% if item.cron|default(dupwrap_cron) %}present\
    {% else %}absent{% endif %}"
  loop: "{{dupwrap_backups}}"

- name: "set cron backup prune"
  cron:
    cron_file: "dupwrap-prune-{{item.name}}"
    name: "yolo prune backups"
    hour: "2"
    weekday: "sunday"
    job: >
      bash -c '{{dupwrap_bin_prefix}}/dupwrap prune -p {{item.name}}
      {% if dupwrap_cron_verbose -%}
      -v &>> {{dupwrap_log_prefix}}/dupwrap.log
      {% else %}
      -q
      {%- endif -%}'
    user: "{{dupwrap_user}}"
    state: "{% if item.cron|default(dupwrap_cron) %}present\
    {% else %}absent{% endif %}"
  loop: "{{dupwrap_backups}}"


- name: "install some helpers"
  copy:
    src: "{{item}}_helper.sh"
    dest: "{{dupwrap_bin_prefix}}/dupwrap-{{item}}-helper"
    owner: "{{dupwrap_user}}"
    group: "{{dupwrap_group}}"
    mode: 0770
  loop: "{{dupwrap_helpers}}"

- include_role:
    name: nickhammond.logrotate
  vars:
    logrotate_scripts:
      - name: "dupwrap-{{item.name}}"
        path: "{{dupwrap_log_prefix}}/dupwrap-{{item.name}}.log"
        options:
          - weekly
          - missingok
          - rotate 4
          - compress
          - "create 0640 {{dupwrap_user}} {{dupwrap_group}}"
  loop: "{{dupwrap_backups}}"

- name: "remove old log file, if present"
  file:
    path: "{{dupwrap_log_prefix}}/dupwrap.log"
    state: "absent"
